# env variables
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - create_file
      - list_file:
         requires:
           - create_file

jobs:
  create_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            touch test-file
            ls
  list_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: cat test-file
